### PR TITLE
[CB-14156] Remove browserify

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

All

### What does this PR do?

The browserify tasks do not seem to work, maybe should be removed in minor version release or maybe major version release.

NOTE that this is WIP NOT TESTED __and known to fail `npm test`__

### What testing has been done on this change?

TODO

### Checklist

- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database - TODO
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected. - TODO
- ~~Added automated test coverage as appropriate for this change.~~

### CODE REVIEW

**Comment by janpio** [comment]
Why? Do you know the reason why this was there and what it was used for in the first place?

**Comment by brodybits** [comment]
I just raised [CB-14156](https://issues.apache.org/jira/browse/CB-14156) to report the problems with `browserify` in general, marking this as the easiest alternative solution.

> Why?

Problems now listed in CB-14156, biggest concern is with duplicated code.

> Do you know the reason why this was there and what it was used for in the first place?

Using `grunt` and `browserify` was more popular 3-4 years ago. Considering it doesn't work for me I suspect the `browserify` target has not been used for quite a while.

**Comment by raphinesse** [comment]
I've taken the liberty to rebase these changes and remove the last traces of browserify that I could find. I also removed the *WIP* in the title, as this is now finished IMHO.

@brodybits Could you explain what you mean by "known to fail `npm test`"? The CI tests all passed.

**Comment by erisu** [comment]
@brodybits @raphinesse 
Is there something that is block this PR?
Is this still targeted for next major?

I just want to make sure it is not forgotten as it appears to be the last item for https://github.com/apache/cordova/issues/8.

**Comment by raphinesse** [comment]
Not from my side. I was waiting for @brodybits to answer the question from my last comment.

**Comment by raphinesse** [comment]
@brodybits I approved the changes since I reviewed and since they passed the automated tests. I did not know whether you wanted to do some manual tests too. That's why I left the *NOT TESTED* in place.

**Comment by brodybits** [comment]
I will go ahead with a quick test then, thanks.

**Comment by brodybits** [comment]
I tested that if I would do `coho copy-js` to include the recent changes in master branch of each platform I am able to run the cordova-sqlite-storage test suite (except for Windows where I tested with https://github.com/brodybits/cordova-dialogs-bootstrap-test). For browser I had to test on edge branch of cordova-sqlite-storage.

**Pull request merged**
