### PR TITLE
breaking(npm): bump dependencies

### PR DESCRIPTION
**Pull request by erisu**
### Motivation and Context

Bring all dependencies up to date (latest).

### Description

Requires #223 to be merged first

**Dev Dependencies**

* `@cordova/eslint-config@^3.0.0`
* `cordova-android@^8.1.0`
* `cordova-ios@^5.1.1`
* `eslint-plugin-es5@^1.5.0`
* `grunt@^1.1.0`
* `jasmine-core@^3.5.0`
* `karma@^4.4.1`
* `karma-chrome-launcher@^3.1.0`
* `karma-coverage@^2.0.1`
* `karma-jasmine@^3.1.1`
* `puppeteer@^2.1.1`

**Dependencies**

* `execa@^4.0.0`
* `fs-extra@^9.0.0`
* `globby@^11.0.0`

Applied `execa` fix.

### Testing

- `npm t`

### Checklist

- [x] I've run the tests to see all new and existing tests pass

### CODE REVIEW

**Comment by erisu** [comment]
@raphinesse 

Karma testing and reporting seems to be functioning properly but an `UncaughtException` error is now being reported and displayed in the terminal output. This appears with the bumped dep. Doesn't seem to be affecting or breaking the tests or reporting.

```log
31 03 2020 08:32:37.974:ERROR [karma-server]: UncaughtException
```

**logLevel=DEBUG**

```log
31 03 2020 17:50:34.930:ERROR [config]: Error in config file!
  Error: Cannot find module '/temp/cordova-js/—logLevel=DEBUG'
Require stack:
- /temp/cordova-js/node_modules/karma/lib/config.js
- /temp/cordova-js/node_modules/karma/lib/server.js
- /temp/cordova-js/node_modules/karma/lib/cli.js
- /temp/cordova-js/node_modules/karma/bin/karma
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
  at Function.Module._load (internal/modules/cjs/loader.js:864:27)
  at Module.require (internal/modules/cjs/loader.js:1044:19)
  at require (internal/modules/cjs/helpers.js:77:18)
  at Object.parseConfig (/temp/cordova-js/node_modules/karma/lib/config.js:357:22)
  at new Server (/temp/cordova-js/node_modules/karma/lib/server.js:67:24)
  at Object.exports.run (/temp/cordova-js/node_modules/karma/lib/cli.js:295:7)
  at Object.<anonymous> (/temp/cordova-js/node_modules/karma/bin/karma:3:23)
  at Module._compile (internal/modules/cjs/loader.js:1158:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
  at Module.load (internal/modules/cjs/loader.js:1002:32)
  at Function.Module._load (internal/modules/cjs/loader.js:901:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
  at internal/main/run_main_module.js:18:47

npm ERR! Test failed.  See above for more details.
```

I am guessing something changes in their configurations but it doesn't nicely say what.

**Comment by raphinesse** [comment]
@erisu I think you gave the wrong commandline option. `npx karma start --log-level debug` gives different output for me. Unfortunately still no details about the uncaught exception.

**Comment by raphinesse** [comment]
@erisu The failure is caused by the major update of `karma-coverage`. Reverting the version change resolved the problem for me. Their list of [breaking changes for v2](https://github.com/karma-runner/karma-coverage/blob/master/CHANGELOG.md#breaking-changes) is quite long.

If you feel so inclined to fix this instead of downgrading, here's where we use the Istanbul API: https://github.com/apache/cordova-js/blob/e8fab0a8767dbb7a76b17f0861c1b6d5b585519d/build-tools/test-build.js#L32

**Comment by erisu** [comment]
```
31 03 2020 11:06:11.607:ERROR [karma-server]: [TypeError: Cannot read property 'start' of undefined
```

**Comment by erisu** [comment]
Coverage is working.

**Comment by raphinesse** [comment]
Three people fixing it at the same time in three different ways :D

https://github.com/apache/cordova-js/commit/3b337e8f0a6808b445e847c4d93f7f9a1e272400

**Comment by raphinesse** [comment]
I basically did the same as @timbru31 but with a comment change and destructuring. Works for me to fix the Uncaught Exception. Why the commit pinning @erisu?

**Comment by erisu** [comment]
@raphinesse that is `master` at current commit id. In `karma-coverage` they updated their dependencies 6 days ago for the reporter.

```diff
-    "istanbul-lib-coverage": "^2.0.5",
-    "istanbul-lib-instrument": "^3.3.0",
-    "istanbul-lib-report": "^2.0.8",
-    "istanbul-lib-source-maps": "^3.0.6",
-    "istanbul-reports": "^2.2.4",
-    "minimatch": "^3.0.0"
+    "istanbul-lib-coverage": "^3.0.0",
+    "istanbul-lib-instrument": "^4.0.1",
+    "istanbul-lib-report": "^3.0.0",
+    "istanbul-lib-source-maps": "^4.0.0",
+    "istanbul-reports": "^3.0.0",
+    "minimatch": "^3.0.4"
```

In these changes, it fixed the error. I didn't want to leave it unpinned to always use lasted master as they might commit a breaking change.

**Comment by raphinesse** [comment]
@erisu But why do we need to use an unreleased version? It is fixed for latest released v2 by Tim's and my changes.

**Comment by erisu** [comment]
@raphinesse @timbru31 PR was pointing to master.

**Comment by timbru31** [comment]
Indeed, the fix with `createInstrumenter` works with the v2.0.1, too

**Pull request merged**
