### PR TITLE
CB-8996 (Windows) Fixed invalid null comparison

### PR DESCRIPTION
**Pull request by alsorokin**
https://issues.apache.org/jira/browse/CB-8996

### CODE REVIEW

**Comment by purplecabbage** [comment]
Status can be 0

**Comment by dblotsky** [comment]
Merged, making it check explicitly for `undefined` and `null`, as per Jesse's note that 0 is a valid return value, and `if(condition)` wasn't sufficient.

**Comment by purplecabbage** [comment]
Looks good!

@purplecabbage
risingj.com

**Comment by purplecabbage** [comment]
ultimately this was a failure of our use of jshint.  
The original check of (undef != null) was fine, but jshint considered it an error ... which led to a fix which caused a real error.

**Pull request closed without merging**
