### PR TITLE
Fixed callbackFromNative method

### PR DESCRIPTION
**Pull request by mdudek**
NO_RESULT status was resolved as failure.

### CODE REVIEW

**Comment by purplecabbage** [comment]
It needs to be done here also: 
https://github.com/apache/cordova-js/blob/master/src/cordova_b.js#L212

**Comment by mdudek** [comment]
Fixed also in cordova_b.js

**Comment by matt-way** [comment]
NO_RESULT doing absolutely nothing in javascript is bad design. For example, now there is no way of telling when/if the cordova-plugin-contacts plugin was cancelled.

**Comment by purplecabbage** [comment]
In the case of the contacts plugin, yes, android should return an error on Activity.RESULT_CANCELED
This is an inappropriate use of NO_RESULT.
Please file an issue in JIRA.

**Comment by matt-way** [comment]
Can you give one good example of when NO_RESULT would ever be useful? What is the difference now between NO_RESULT and actually not doing anything?

**Pull request merged**
