### PR TITLE
CB-9057: Updated cordova.js for Windows to refer to base.js instead of winjs.js

### PR DESCRIPTION
**Pull request by robpaveza**
Fixed this change for cordova-js as well as in cordova-windows.

### CODE REVIEW

**Comment by nikhilkh** [comment]
@stevengill - What is the correct way to make a corodova.js change now?

**Comment by stevengill** [comment]
The correct way is to change it in cordova-windows now.  You can still update legacy-exec cordovajs version but it won't be used when building cordova.js anymore and will eventually be removed.

**Comment by nikhilkh** [comment]
Thanks, Steve! I think createmobilespec might need an update for this to work. In general, what's the recommended workflow for us to generate cordova.js for a particular platform? Would you use npm link after your recent set of changes?

**Comment by stevengill** [comment]
If you make changes to the platform specific js and want to test it out, I would npm link it to the one in cordova.js/node_modules/platform to test. When we do platform/tools releases, we should make sure the dependency in cordova.js gets updated.

**Pull request merged**
